---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-data
  namespace: "$NAMESPACE"
spec:
  volumeName: share-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/local-path-provisioner/share-data
    type: DirectoryOrCreate
  claimRef:
    name: share-data
    namespace: "$NAMESPACE"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: "$NAMESPACE"
spec:
  volumeName: logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
spec:
  capacity:
    storage: 32Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/local-path-provisioner/logs
    type: DirectoryOrCreate
  claimRef:
    name: logs
    namespace: "$NAMESPACE"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: "$NAMESPACE"
spec:
  volumeName: mysql-pv-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/local-path-provisioner/mysql-pv-claim
    type: DirectoryOrCreate
  claimRef:
    name: mysql-pv-claim
    namespace: "$NAMESPACE"
