---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-data
spec:
  storageClassName: {{ .Values.storageClassName | default "rbd" }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  storageClassName: {{ .Values.storageClassName | default "rbd" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  volumeName: data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /run/k8s/aic_data_mnt
    type: DirectoryOrCreate
  claimRef:
    name: data
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-data
spec:
  volumeName: private-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: private-data
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/local-path-provisioner/private-data
    type: DirectoryOrCreate
  claimRef:
    name: private-data
    namespace: default