{
 "title": "Android Cloud Dashboard",
 "description": "Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": "label_values(origin_prometheus)"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
   },
   {
    "name": "NameSpace",
    "label": "NameSpace",
    "query": "label_values(kube_namespace_labels{origin_prometheus=~\"$origin_prometheus\"},namespace)"
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
   },
   {
    "name": "Container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\"},container)"
   },
   {
    "name": "collector_pods",
    "label": "collector_pods",
    "query": "label_values(node_namespace_pod:kube_pod_info:{namespace=~\"monitoring\",node=~\"$show_hostname\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Resource Details：【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used RAM Memory"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
       "legendFormat": "Used Max Mount($maxmount)"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
       "legendFormat": "Used SWAP"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic(EXT/XFS)",
     "type": "table-old",
     "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
     "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
       "legendFormat": "总量"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
      }
     ]
    },
    {
     "title": "CPU iowait",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) * 100"
      }
     ]
    },
    {
     "title": "[$device]: Internet traffic per hour",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
     "yaxes": [
      { "format": "bytes", "label": "transmit（-）/receive（+）" }
     ],
     "targets": [
      {
       "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
       "legendFormat": "{{device}}_receive"
      },
      {
       "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
       "legendFormat": "{{device}}_transmit"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
      }
     ]
    },
    {
     "title": "Free inodes:$maxmount ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_filesystem_files_free{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total filefd",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 15, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "CPU% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "Avaliable"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used%"
      }
     ]
    },
    {
     "title": "[$device]: Network bandwidth usage per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "bps", "label": "transmit（-）/receive（+）" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
       "legendFormat": "{{device}}_receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
       "legendFormat": "{{device}}_transmit"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}",
       "legendFormat": "15m"
      },
      {
       "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
       "legendFormat": "CPU cores"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Written bytes"
      }
     ]
    },
    {
     "title": "Disk Space Used% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOps Completed（IOPS）",
     "type": "graph",
     "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Writes completed"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_ IO time"
      }
     ]
    },
    {
     "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
     "type": "graph",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "Time read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Read time"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Write time"
      }
     ]
    },
    {
     "title": "Network Sockstat",
     "type": "graph",
     "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "TCP_tw"
      },
      {
       "expr": "node_sockstat_sockets_used{instance=~'$node'}",
       "legendFormat": "Sockets_used"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
       "legendFormat": "UDP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "rate(node_netstat_Tcp_InSegs{instance=~'$node'}[$interval])",
       "legendFormat": "Tcp_InSegs"
      },
      {
       "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'$node'}[$interval])",
       "legendFormat": "Tcp_OutSegs"
      },
      {
       "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[$interval])",
       "legendFormat": "Tcp_RetransSegs"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "used filefd" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}",
       "legendFormat": "used filefd"
      },
      {
       "expr": "rate(node_context_switches_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "switches"
      }
     ]
    },
    {
     "title": "Pod [$Pod]: Resource Details",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"} == 1"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container, pod)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container, pod)",
       "legendFormat": "CPU core usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"} - 0"
      },
      {
       "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_noheap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_noheap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      }
     ]
    },
    {
     "title": "Container [$Container]: Resource Details",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "Overall audit usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "Average memory% (RSS)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Total memory usage (RSS)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container) - 0"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Resource Details: 【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU GT Frequency/MHz",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "GPUD128GTFreq_MHZ{pod=~\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD129GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD130GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD131GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD132GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD133GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD134GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD135GTFreq_MHZ{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "GPU Render Usage%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "GPUD128RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD129RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD130RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD131RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD132RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD133RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD134RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD135RenderLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "GPU VideoE Usage%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "GPUD128VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD129VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD130VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD131VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD132VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD133VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD134VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD135VideoELoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "GPU Video2 Usage%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "GPUD128Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD129Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD130Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD131Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD132Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD133Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD134Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD135Video2Load_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      }
     ]
    },
    {
     "title": "GPU Video Usage%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "GPUD128VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD129VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD130VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD131VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD132ideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD133VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD134VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      },
      {
       "expr": "GPUD135VideoLoad_{pod=\"$collector_pods\"}",
       "legendFormat": "{{userid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Android Pod CPU Usage Details: ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU Usage%",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"android.+\"}[1m])) by (pod) * 100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}