apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: {{ .Values.storageClassName | default "rbd" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi