apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: "$NAMESPACE"
spec:
  volumeName: data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: "$NAMESPACE"
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /run/k8s/aic_data_mnt
    type: DirectoryOrCreate
  claimRef:
    name: data
    namespace: "$NAMESPACE"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-data
  namespace: "$NAMESPACE"
spec:
  volumeName: private-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: private-data
  namespace: "$NAMESPACE"
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/local-path-provisioner/private-data
    type: DirectoryOrCreate
  claimRef:
    name: private-data
    namespace: "$NAMESPACE"
