#!/usr/bin/env bash
# author: ziniu.lin
#
# Copyright (C) 2018 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials,
# and your use of them is governed by the express license under which they
# were provided to you (End User License Agreement for the Intel(R) Software
# Development Products (Version September 2018)). Unless the License provides
# otherwise, you may not use, modify, copy, publish, distribute, disclose or
# transmit this software or the related documents without Intel's prior
# written permission.
#
# This software and the related documents are provided as is, with no
# express or implied warranties, other than those that are expressly
# stated in the License.
#

USERNAME="DEFAULT"
PASSWORD="DEFAULT"
REGISTRY="DEFAULT"

function usage() {
    local self=$(basename $0)
    cat <<EOF
Usage: $self [-u|--username <username>] [-p|--password <password>] [-r|--registry <registry_addr>] [-h|--help]
EOF
}

function msg {
    echo "> $@"
}

while [ "$#" -gt 0 ]; do
    case "$1" in
    -u | --username)
        shift
        USERNAME=$1
        shift
        ;;
    -p | --password)
        shift
        PASSWORD=$1
        shift
        ;;
    -r | --registry)
        shift
        REGISTRY=$1
        shift
        ;;
    -h | --help)
        shift
        usage
        exit 1
        shift
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ $USERNAME == "DEFAULT" ] || [ $PASSWORD == "DEFAULT" ] || [ $REGISTRY == "DEFAULT" ]; then
    usage
    exit 1
fi

msg "Generating harbor registry secrets for $REGISTRY"
msg "Username: $USERNAME"
msg "Password: $PASSWORD"

msg "Creating docker pull secret"
kubectl create secret docker-registry harbor-registry-key --docker-server=$REGISTRY --docker-username=$USERNAME --docker-password=$PASSWORD

kubectl get serviceaccounts default -o yaml > ./sa.yaml
echo "imagePullSecrets:" >> ./sa.yaml
echo "- name: harbor-registry-key" >> ./sa.yaml

msg "Updating service account"
kubectl replace serviceaccount default -f ./sa.yaml

msg "Docker login"
docker login $REGISTRY -u $USERNAME -p $PASSWORD

msg "Creating harbor api key"
KEY=$(echo -n $USERNAME:$PASSWORD | base64 -w 0)
cp -f ./harbor-secret.yaml ./harbor_secret_update.yaml
sed -in "s|\$HARBOR-KEY|${KEY}|" ./harbor_secret_update.yaml
kubectl apply -f ./harbor_secret_update.yaml

msg "Complete"
