apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFCbDhnbGd5OEdvQWhBQTRpVk9pTk1tcDMrdzRvamp2ekw2eGc9PQ==
