apiVersion: v1
data:
  # HOST=$(hostname)
  # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "key.toml" -out "crt.toml" -subj "/CN=${HOST}/O=${HOST}"
  tls.crt: {{ .Files.Get "crt.toml" | b64enc }}
  tls.key: {{ .Files.Get "key.toml" | b64enc }}
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
