---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-data
  namespace: "$NAMESPACE"
spec:
  storageClassName: rbd
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: "$NAMESPACE"
spec:
  storageClassName: rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: "$NAMESPACE"
spec:
  storageClassName: rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
