-----BEGIN CERTIFICATE-----
MIIDPzCCAiegAwIBAgIJAJIhs3gVQs2sMA0GCSqGSIb3DQEBCwUAMDYxGTAXBgNV
BAMMEHplbmctazhzbWFzdGVyMDExGTAXBgNVBAoMEHplbmctazhzbWFzdGVyMDEw
HhcNMjIwOTIyMTY0OTU0WhcNMjMwOTIyMTY0OTU0WjA2MRkwFwYDVQQDDBB6ZW5n
LWs4c21hc3RlcjAxMRkwFwYDVQQKDBB6ZW5nLWs4c21hc3RlcjAxMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArgpenDboqXtxvKzLGuNz3JFg8c1H8BH/
rYbrx3W9Eh4vhpqudZPxfGcGx2hIbYyS30nZYUdmmDRy4qbiEb4r1RmW5gyGKRgE
YNjcg44Jl4C8dV5eZcnXq2zGYNfySvnfszi+7Wul/D/mHkTZL82w7P/hGx24stm9
Ecm3La7kd3kD4NxiiWvYoZqmZxGGnKJjZA3BcBZojNv4Ca+HQeHwLwFB8EOGn00M
YXlfatrU6LOT/09m/+63qshQyy4ps2Y4KD6o9jhbDtIbZe93OdckaHZem2O3PpTx
mBp7tKGOzDzjF7Y0lRTeYO9ctq8OyKNlSwDtWDlOOgHwzeTM0jfCxQIDAQABo1Aw
TjAdBgNVHQ4EFgQUzsB+hCf3X1+9S0dRq3IPJHokg+MwHwYDVR0jBBgwFoAUzsB+
hCf3X1+9S0dRq3IPJHokg+MwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
AQEATcNsJOR32tnrPI0VfSMB9DdmNBSITy8eMsbWeTY5yLjcFWHWeSQE1KAmBONY
7+Lt3y4kJ4y7WbttXA7v6LD3I7Fc9wO6fGmTArWPevrpAp7olYuRJ6HNZyomcGiu
ooAhDTi7SBh8TDbzt8lRur/1+wHyJMWUnqb+lJ20QUykdzH63LOe6thbgm6qQprk
LzmzJBwrnrYG2vWKfZurxS4/Y0PtR4CBNBzD0KcIYuVYQBYET0gVQy3fAUpfTL6L
8wAR3PKSes9p/YsTuS5i3cyAX0jvSMMNQyZ/trm2Kz52BNVXqsdoiWzuQrXKi3SW
YbnzYOW8GxBsXxK5D7WWKcHpaQ==
-----END CERTIFICATE-----
